experiment_name: nbinom_ensemble
accelerator: cpu
batch_size: 128
member_head_type: negative_binomial
members:
  - chkp/discrete-wave/nbinom/version_0/best_loss.ckpt
  - chkp/discrete-wave/nbinom/version_1/best_loss.ckpt
  - chkp/discrete-wave/nbinom/version_2/best_loss.ckpt
  - chkp/discrete-wave/nbinom/version_3/best_loss.ckpt
  - chkp/discrete-wave/nbinom/version_4/best_loss.ckpt
dataset:
  type: tabular
  spec: data/discrete-wave/discrete_sine_wave.npz
log_dir: results/discrete-wave/ensembles
