experiment_name: beta_ddpn_0.5_ensemble
accelerator: gpu
batch_size: 256
member_head_type: double_poisson
members:
  - chkp/coco-people/beta_ddpn_0.5/version_0/best_loss.ckpt
  - chkp/coco-people/beta_ddpn_0.5/version_1/best_loss.ckpt
  - chkp/coco-people/beta_ddpn_0.5/version_2/best_loss.ckpt
  - chkp/coco-people/beta_ddpn_0.5/version_3/best_loss.ckpt
  - chkp/coco-people/beta_ddpn_0.5/version_4/best_loss.ckpt
dataset:
  type: image
  spec: coco_people
log_dir: results/coco-people/ensembles
