experiment_name: ddpn_ensemble
accelerator: gpu
batch_size: 256
member_head_type: double_poisson
members:
  - chkp/coco-people/ddpn/version_0/best_loss.ckpt
  - chkp/coco-people/ddpn/version_1/best_loss.ckpt
  - chkp/coco-people/ddpn/version_2/best_loss.ckpt
  - chkp/coco-people/ddpn/version_3/best_loss.ckpt
  - chkp/coco-people/ddpn/version_4/best_loss.ckpt
dataset:
  type: image
  spec: coco_people
log_dir: results/coco-people/ensembles
