experiment_name: nbinom_ensemble
accelerator: gpu
batch_size: 256
member_head_type: negative_binomial
members:
  - chkp/coco-people/nbinom/version_0/best_loss.ckpt
  - chkp/coco-people/nbinom/version_1/best_loss.ckpt
  - chkp/coco-people/nbinom/version_2/best_loss.ckpt
  - chkp/coco-people/nbinom/version_3/best_loss.ckpt
  - chkp/coco-people/nbinom/version_4/best_loss.ckpt
dataset:
  type: image
  spec: coco_people
log_dir: results/coco-people/ensembles
