experiment_name: poisson_ensemble
accelerator: gpu
batch_size: 256
member_head_type: poisson
members:
  - chkp/coco-people/poisson/version_0/best_loss.ckpt
  - chkp/coco-people/poisson/version_1/best_loss.ckpt
  - chkp/coco-people/poisson/version_2/best_loss.ckpt
  - chkp/coco-people/poisson/version_3/best_loss.ckpt
  - chkp/coco-people/poisson/version_4/best_loss.ckpt
dataset:
  type: image
  spec: coco_people
log_dir: results/coco-people/ensembles
