experiment_name: stirn_ensemble
accelerator: gpu
batch_size: 256
member_head_type: faithful_gaussian
members:
  - chkp/coco-people/stirn/version_0/best_loss.ckpt
  - chkp/coco-people/stirn/version_1/best_loss.ckpt
  - chkp/coco-people/stirn/version_2/best_loss.ckpt
  - chkp/coco-people/stirn/version_3/best_loss.ckpt
  - chkp/coco-people/stirn/version_4/best_loss.ckpt
dataset:
  type: image
  spec: coco_people
log_dir: results/coco-people/ensembles
