experiment_name: ddpn_ensemble
accelerator: cpu
batch_size: 32
member_head_type: double_poisson
members:
  - chkp/bikes/ddpn/version_0/best_loss.ckpt
  - chkp/bikes/ddpn/version_1/best_loss.ckpt
  - chkp/bikes/ddpn/version_2/best_loss.ckpt
  - chkp/bikes/ddpn/version_3/best_loss.ckpt
  - chkp/bikes/ddpn/version_4/best_loss.ckpt
dataset:
  type: tabular
  spec: data/bikes/bikes.npz
log_dir: results/bikes/ensembles
