experiment_name: dpo_glm_ensemble
accelerator: cpu
batch_size: 32
member_head_type: double_poisson_glm
members:
  - chkp/bikes/dpo_glm/version_0/best_loss.ckpt
  - chkp/bikes/dpo_glm/version_1/best_loss.ckpt
  - chkp/bikes/dpo_glm/version_2/best_loss.ckpt
  - chkp/bikes/dpo_glm/version_3/best_loss.ckpt
  - chkp/bikes/dpo_glm/version_4/best_loss.ckpt
dataset:
  type: tabular
  spec: data/bikes/bikes.npz
log_dir: results/bikes/ensembles
