experiment_name: gaussian_ensemble
accelerator: cpu
batch_size: 32
member_head_type: log_gaussian
members:
  - chkp/bikes/gaussian/version_0/best_loss.ckpt
  - chkp/bikes/gaussian/version_1/best_loss.ckpt
  - chkp/bikes/gaussian/version_2/best_loss.ckpt
  - chkp/bikes/gaussian/version_3/best_loss.ckpt
  - chkp/bikes/gaussian/version_4/best_loss.ckpt
dataset:
  type: tabular
  spec: data/bikes/bikes.npz
log_dir: results/bikes/ensembles
