experiment_name: nbinom_ensemble
accelerator: cpu
batch_size: 32
member_head_type: negative_binomial
members:
  - chkp/bikes/nbinom/version_0/best_loss.ckpt
  - chkp/bikes/nbinom/version_1/best_loss.ckpt
  - chkp/bikes/nbinom/version_2/best_loss.ckpt
  - chkp/bikes/nbinom/version_3/best_loss.ckpt
  - chkp/bikes/nbinom/version_4/best_loss.ckpt
dataset:
  type: tabular
  spec: data/bikes/bikes.npz
log_dir: results/bikes/ensembles
