experiment_name: poisson_ensemble
accelerator: cpu
batch_size: 32
member_head_type: poisson
members:
  - chkp/bikes/poisson/version_0/best_loss.ckpt
  - chkp/bikes/poisson/version_1/best_loss.ckpt
  - chkp/bikes/poisson/version_2/best_loss.ckpt
  - chkp/bikes/poisson/version_3/best_loss.ckpt
  - chkp/bikes/poisson/version_4/best_loss.ckpt
dataset:
  type: tabular
  spec: data/bikes/bikes.npz
log_dir: results/bikes/ensembles
