experiment_name: seitzer_1.0_ensemble
accelerator: cpu
batch_size: 32
member_head_type: log_gaussian
members:
  - chkp/bikes/seitzer_1.0/version_0/best_loss.ckpt
  - chkp/bikes/seitzer_1.0/version_1/best_loss.ckpt
  - chkp/bikes/seitzer_1.0/version_2/best_loss.ckpt
  - chkp/bikes/seitzer_1.0/version_3/best_loss.ckpt
  - chkp/bikes/seitzer_1.0/version_4/best_loss.ckpt
dataset:
  type: tabular
  spec: data/bikes/bikes.npz
log_dir: results/bikes/ensembles
