experiment_name: stirn_ensemble
accelerator: cpu
batch_size: 32
member_head_type: log_faithful_gaussian
members:
  - chkp/bikes/stirn/version_0/best_loss.ckpt
  - chkp/bikes/stirn/version_1/best_loss.ckpt
  - chkp/bikes/stirn/version_2/best_loss.ckpt
  - chkp/bikes/stirn/version_3/best_loss.ckpt
  - chkp/bikes/stirn/version_4/best_loss.ckpt
dataset:
  type: tabular
  spec: data/bikes/bikes.npz
log_dir: results/bikes/ensembles
