experiment_name: immer_ensemble
accelerator: cpu
batch_size: 32
member_head_type: natural_gaussian
members:
  - chkp/collisions/immer/version_0/best_loss.ckpt
  - chkp/collisions/immer/version_1/best_loss.ckpt
  - chkp/collisions/immer/version_2/best_loss.ckpt
  - chkp/collisions/immer/version_3/best_loss.ckpt
  - chkp/collisions/immer/version_4/best_loss.ckpt
dataset:
  type: tabular
  spec: data/collisions/collisions.npz
log_dir: results/collisions/ensembles
