experiment_name: nbinom_glm_ensemble
accelerator: cpu
batch_size: 32
member_head_type: negative_binomial_glm
members:
  - chkp/collisions/nbinom_glm/version_0/best_loss.ckpt
  - chkp/collisions/nbinom_glm/version_1/best_loss.ckpt
  - chkp/collisions/nbinom_glm/version_2/best_loss.ckpt
  - chkp/collisions/nbinom_glm/version_3/best_loss.ckpt
  - chkp/collisions/nbinom_glm/version_4/best_loss.ckpt
dataset:
  type: tabular
  spec: data/collisions/collisions.npz
log_dir: results/collisions/ensembles
