experiment_name: seitzer_1.0_ensemble
accelerator: cpu
batch_size: 32
member_head_type: gaussian
members:
  - chkp/collisions/seitzer_1.0/version_0/best_loss.ckpt
  - chkp/collisions/seitzer_1.0/version_1/best_loss.ckpt
  - chkp/collisions/seitzer_1.0/version_2/best_loss.ckpt
  - chkp/collisions/seitzer_1.0/version_3/best_loss.ckpt
  - chkp/collisions/seitzer_1.0/version_4/best_loss.ckpt
dataset:
  type: tabular
  spec: data/collisions/collisions.npz
log_dir: results/collisions/ensembles
