experiment_name: stirn_ensemble
accelerator: cpu
batch_size: 32
member_head_type: faithful_gaussian
members:
  - chkp/collisions/stirn/version_0/best_loss.ckpt
  - chkp/collisions/stirn/version_1/best_loss.ckpt
  - chkp/collisions/stirn/version_2/best_loss.ckpt
  - chkp/collisions/stirn/version_3/best_loss.ckpt
  - chkp/collisions/stirn/version_4/best_loss.ckpt
dataset:
  type: tabular
  spec: data/collisions/collisions.npz
log_dir: results/collisions/ensembles
