experiment_name: stirn
random_seed: 1998
head_type: faithful_gaussian
dataset:
  type: image
  spec: coco_people
training:
  accelerator: gpu
  batch_size: 128
  chkp_dir: chkp/coco-people
  chkp_freq: 10
  num_epochs: 10
  precision: bf16-mixed
  optimizer:
    type: adam_w
    kwargs:
      lr: 0.0001
      weight_decay: 0.001
  lr_scheduler:
    type: cosine_annealing
    kwargs:
      T_max: 10
      eta_min: 0
      last_epoch: -1
evaluation:
  num_trials: 5
  log_dir: logs/coco-people
