experiment_name: poisson_ensemble
accelerator: cpu
batch_size: 32
member_head_type: poisson
members:
  - chkp/length-of-stay/poisson/version_0/best_loss.ckpt
  - chkp/length-of-stay/poisson/version_1/best_loss.ckpt
  - chkp/length-of-stay/poisson/version_2/best_loss.ckpt
  - chkp/length-of-stay/poisson/version_3/best_loss.ckpt
  - chkp/length-of-stay/poisson/version_4/best_loss.ckpt
dataset:
  type: tabular
  spec: data/length-of-stay/length_of_stay.npz
log_dir: results/length-of-stay/ensembles
