experiment_name: ddpn_ensemble
accelerator: gpu
batch_size: 256
member_head_type: double_poisson
members:
  - chkp/reviews/ddpn/version_0/best_loss.ckpt
  - chkp/reviews/ddpn/version_1/best_loss.ckpt
  - chkp/reviews/ddpn/version_2/best_loss.ckpt
  - chkp/reviews/ddpn/version_3/best_loss.ckpt
  - chkp/reviews/ddpn/version_4/best_loss.ckpt
dataset:
  type: text
  spec: reviews
log_dir: results/reviews/ensembles
