experiment_name: gaussian_ensemble
accelerator: gpu
batch_size: 32
member_head_type: gaussian
members:
  - chkp/reviews/gaussian/version_0/best_loss.ckpt
  - chkp/reviews/gaussian/version_1/best_loss.ckpt
  - chkp/reviews/gaussian/version_2/best_loss.ckpt
  - chkp/reviews/gaussian/version_3/best_loss.ckpt
  - chkp/reviews/gaussian/version_4/best_loss.ckpt
dataset:
  type: text
  spec: reviews
log_dir: results/reviews/ensembles
