experiment_name: immer_ensemble
accelerator: gpu
batch_size: 256
member_head_type: natural_gaussian
members:
  - chkp/reviews/immer/version_0/best_loss.ckpt
  - chkp/reviews/immer/version_1/best_loss.ckpt
  - chkp/reviews/immer/version_2/best_loss.ckpt
  - chkp/reviews/immer/version_3/best_loss.ckpt
  - chkp/reviews/immer/version_4/best_loss.ckpt
dataset:
  type: text
  spec: reviews
log_dir: results/reviews/ensembles
