experiment_name: poisson_ensemble
accelerator: gpu
batch_size: 32
member_head_type: poisson
members:
  - chkp/reviews/poisson/version_0/best_loss.ckpt
  - chkp/reviews/poisson/version_1/best_loss.ckpt
  - chkp/reviews/poisson/version_2/best_loss.ckpt
  - chkp/reviews/poisson/version_3/best_loss.ckpt
  - chkp/reviews/poisson/version_4/best_loss.ckpt
dataset:
  type: text
  spec: reviews
log_dir: results/reviews/ensembles
