experiment_name: seitzer_0.5_ensemble
accelerator: gpu
batch_size: 32
member_head_type: gaussian
members:
  - chkp/reviews/seitzer_0.5/version_0/best_loss.ckpt
  - chkp/reviews/seitzer_0.5/version_1/best_loss.ckpt
  - chkp/reviews/seitzer_0.5/version_2/best_loss.ckpt
  - chkp/reviews/seitzer_0.5/version_3/best_loss.ckpt
  - chkp/reviews/seitzer_0.5/version_4/best_loss.ckpt
dataset:
  type: text
  spec: reviews
log_dir: results/reviews/ensembles
