experiment_name: stirn_ensemble
accelerator: gpu
batch_size: 32
member_head_type: faithful_gaussian
members:
  - chkp/reviews/stirn/version_0/last.ckpt
  - chkp/reviews/stirn/version_1/last.ckpt
  - chkp/reviews/stirn/version_2/last.ckpt
  - chkp/reviews/stirn/version_3/last.ckpt
  - chkp/reviews/stirn/version_4/last.ckpt
dataset:
  type: text
  spec: reviews
log_dir: results/reviews/ensembles
